version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
  
    steps:
      - checkout
      
      - run: mkdir test-reports
      
      - run:
          name: Restore
          command: dotnet restore
          working_directory: circleCIDunchyk
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: circleCIDunchyk
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: primeCircle.Tests
