version: 2
jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.0
        auth:
          username: root
  
    steps:
      - checkout
      
      - run: mkdir test-reports
          
      - run:
          name: Restore
          command: dotnet restore
          working_directory: primeCircle
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: primeCircle
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: primeCircle.Tests
