version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0-browsers
  
    steps:
      - checkout
      
      - run: mkdir test-reports
      
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
          
      - run:
          name: Restore
          command: dotnet restore
          working_directory: primeCircle
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: primeCircle
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: primeCircle.Tests
